/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acuario;

import Conector.PostgreSQL;
import com.toedter.calendar.JCalendar;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo D'isidoro
 */
public class Evento extends javax.swing.JFrame {
    /**
     * Creates new form Evento
     */
    public Evento() {
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jTextField1 = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        codigoCampo = new javax.swing.JTextField();
        pez = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        estadoCampo = new javax.swing.JTextField();
        fechaCampo = new com.toedter.calendar.JDateChooser();
        pezCampo = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evento");
        setResizable(false);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");

        eliminar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        volver.setText("Regresar");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mantenimiento Evento");

        codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo.setText("Codigo");

        pez.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pez.setText("Pez");

        estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estado.setText("Estado");

        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setText("Fecha");

        fechaCampo.setDateFormatString("yyyy/MM/dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigoCampo)
                            .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pezCampo)
                            .addComponent(pez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estadoCampo, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo)
                    .addComponent(pez)
                    .addComponent(estado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pezCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(fecha)
                .addGap(18, 18, 18)
                .addComponent(fechaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(modificar)
                    .addComponent(eliminar))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar)
                    .addComponent(limpiar)
                    .addComponent(volver))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
            if("".equals(codigoCampo.getText()) || "".equals(estadoCampo.getText()) || "".equals(fechaCampo.getDate()) || "".equals(pezCampo.getText())){
                JOptionPane.showMessageDialog( null, "Actualizacion Fallido\nAsegurese de completar todos los campos","Actualizacion Fallido",JOptionPane.ERROR_MESSAGE );
            }else{
                if(Validador.numeros(codigoCampo.getText()) == 0 || Validador.numeros(pezCampo.getText()) == 0){
                JOptionPane.showMessageDialog( null, "Dato Erroneo\nSolo digite numeros en el campo Codigo","Dato Erroneo",JOptionPane.ERROR_MESSAGE );
                }else{
                    int pez = Integer.parseInt(pezCampo.getText());
                    int cod = Integer.parseInt(codigoCampo.getText());
                    String estado = estadoCampo.getText();
                    DateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
                    java.util.Date fechautil = fechaCampo.getDate();
                    
                    String fecha = formato.format(fechautil);
                    System.out.println(fecha);
                    String sql = "INSERT INTO evento (idevt,idpez,fechaevt,estadoevt) VALUES ("+cod+","+pez+",'"+fecha+"','"+estado+"');";
                    if(PostgreSQL.actualizar(sql)==1){
                    JOptionPane.showMessageDialog( null, "Guardado Exitoso\nSe ha guardado con éxito el nuevo evento","Guardado Exitoso",JOptionPane.INFORMATION_MESSAGE );
                    }else{
                    JOptionPane.showMessageDialog( null, "Guardado Fallido\nVerifique que el código no haya sido ingresado para otro evento","Guardado Fallido",JOptionPane.ERROR_MESSAGE );
                    }
                }
            }
    }//GEN-LAST:event_guardarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        codigoCampo.setText(null);
        estadoCampo.setText(null);
        fechaCampo.setDate(null);
    }//GEN-LAST:event_limpiarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
            if("".equals(codigoCampo.getText()) || "".equals(estadoCampo.getText()) || "".equals(fechaCampo.getDate()) || "".equals(pezCampo.getText())){
                JOptionPane.showMessageDialog( null, "Actualizacion Fallido\nAsegurese de completar todos los campos","Actualizacion Fallido",JOptionPane.ERROR_MESSAGE );
            }else{
                if(Validador.numeros(codigoCampo.getText()) == 0 || Validador.numeros(pezCampo.getText()) == 0){
                JOptionPane.showMessageDialog( null, "Dato Erroneo\nSolo digite numeros en el campo Codigo","Dato Erroneo",JOptionPane.ERROR_MESSAGE );
                }else{
                    int pez = Integer.parseInt(pezCampo.getText());
                    int cod = Integer.parseInt(codigoCampo.getText());
                    String estado = estadoCampo.getText();
                    java.util.Date fecha = fechaCampo.getDate();
                    String sql = "UPDATE evento SET estadoevt='"+estado+"', fechaevt='"+fecha+"',idpez="+pez+" WHERE idevt="+cod;
                    if(PostgreSQL.actualizar(sql)==1){
                    JOptionPane.showMessageDialog( null, "Actualizacion Exitosa\nSe ha actualizado con éxito el evento","Actualizacion Exitosa",JOptionPane.INFORMATION_MESSAGE );
                    }else{
                    JOptionPane.showMessageDialog( null, "Actualizacion Fallida\nVerifique que el código haya sido ingresado para un evento","Actualizacion Fallida",JOptionPane.ERROR_MESSAGE );
                    }
                }
            }
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        if("".equalsIgnoreCase(codigoCampo.getText())){
                JOptionPane.showMessageDialog( null, "Borrado Fallido\nAsegurese de completar el campo:\nCodigo","Borrado Fallido",JOptionPane.ERROR_MESSAGE );
        }else{
            if(Validador.numeros(codigoCampo.getText()) == 0){
                JOptionPane.showMessageDialog( null, "Dato Erroneo\nSolo digite numeros en el campo Codigo","Dato Erroneo",JOptionPane.ERROR_MESSAGE );
            }else{
                    int cod = Integer.parseInt(codigoCampo.getText());
                    String sql="DELETE FROM evento WHERE idevt="+cod;
                    if(PostgreSQL.actualizar(sql)==1){
                    JOptionPane.showMessageDialog( null, "Borrado Exitoso\nSe ha borado con éxito el evento","Borrado Exitoso",JOptionPane.INFORMATION_MESSAGE );
                    }else{
                    JOptionPane.showMessageDialog( null, "Borrado Fallido\nVerifique que el código haya sido ingresado para un evento","Borrado Fallido",JOptionPane.ERROR_MESSAGE );
                    }
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JLabel codigo;
    private javax.swing.JTextField codigoCampo;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel estado;
    private javax.swing.JTextField estadoCampo;
    private javax.swing.JLabel fecha;
    private com.toedter.calendar.JDateChooser fechaCampo;
    private javax.swing.JButton guardar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    private javax.swing.JLabel pez;
    private javax.swing.JTextField pezCampo;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
