/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acuario;

import Conector.PostgreSQL;
import java.sql.Connection;
import java.sql.Statement;
import Objetos.Imagen;
import Objetos.Reporte;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo D'isidoro
 */
public class Menu extends javax.swing.JFrame {
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        pintar();
    }
    
    public void pintar(){
        imagenP.removeAll();
        imagenP.repaint();
        Imagen foto = new Imagen();
        imagenP.add(foto);
        imagenP.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        imagenP = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        Esp = new javax.swing.JMenuItem();
        Tan = new javax.swing.JMenuItem();
        Pez = new javax.swing.JMenuItem();
        Evt = new javax.swing.JMenuItem();
        consulta = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        reportes = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenu();
        salida = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AcquaLand");
        setResizable(false);

        javax.swing.GroupLayout imagenPLayout = new javax.swing.GroupLayout(imagenP);
        imagenP.setLayout(imagenPLayout);
        imagenPLayout.setHorizontalGroup(
            imagenPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        imagenPLayout.setVerticalGroup(
            imagenPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        archivo.setText("Archivo");

        Esp.setText("Especie");
        Esp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspActionPerformed(evt);
            }
        });
        archivo.add(Esp);

        Tan.setText("Tanque");
        Tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanActionPerformed(evt);
            }
        });
        archivo.add(Tan);

        Pez.setText("Pez");
        Pez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PezActionPerformed(evt);
            }
        });
        archivo.add(Pez);

        Evt.setText("Evento");
        Evt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtActionPerformed(evt);
            }
        });
        archivo.add(Evt);

        jMenuBar1.add(archivo);

        consulta.setText("Consulta");

        jMenuItem1.setText("Especie");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        consulta.add(jMenuItem1);

        jMenuItem2.setText("Tanque");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        consulta.add(jMenuItem2);

        jMenuItem3.setText("Pez");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        consulta.add(jMenuItem3);

        jMenuItem5.setText("Evento");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        consulta.add(jMenuItem5);

        jMenuBar1.add(consulta);

        reportes.setText("Reportes");

        jMenuItem6.setText("Especie");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        reportes.add(jMenuItem6);

        jMenuItem7.setText("Tanque");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        reportes.add(jMenuItem7);

        jMenuItem8.setText("Pez");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        reportes.add(jMenuItem8);

        jMenuItem9.setText("Evento");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        reportes.add(jMenuItem9);

        jMenuBar1.add(reportes);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        salida.setText("Salida");
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        salir.add(salida);

        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        
    }//GEN-LAST:event_salirActionPerformed

    private void EspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspActionPerformed
        dispose();
        new Especie().setVisible(true);
    }//GEN-LAST:event_EspActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
       PostgreSQL.logout();
        System.exit(0);
    }//GEN-LAST:event_salidaActionPerformed

    private void TanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanActionPerformed
        dispose();
        new Tanque().setVisible(true);
    }//GEN-LAST:event_TanActionPerformed

    private void PezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PezActionPerformed
        dispose();
        new Pez().setVisible(true);
    }//GEN-LAST:event_PezActionPerformed

    private void EvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtActionPerformed
        dispose();
        new Evento().setVisible(true);
    }//GEN-LAST:event_EvtActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        buscar tabla;
        String sql="SELECT * FROM especie;";
        tabla = new buscar(sql,new Object[]{"ID","Nombre","Alimento"},1);
        tabla.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        buscar tabla;
        String sql="SELECT * FROM tanque;";
        tabla = new buscar(sql,new Object[]{"ID","Nombre","Color","Volumen"},2);
        tabla.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        buscar tabla;
        String sql="SELECT pez.idpez,pez.nombrepez,pez.colorpez,pez.pesopez,especie.nombreesp,tanque.nombretan FROM pez,especie,tanque WHERE pez.idesp = especie.idesp AND pez.idtan = tanque.idtan;";
        tabla = new buscar(sql,new Object[]{"ID","Nombre","Color","Peso","Especie","Tanque"},3);
        tabla.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        buscar tabla;
        String sql="SELECT pez.nombrepez,fechaevt,estadoevt,idevt FROM evento,pez WHERE pez.idpez=evento.idpez;";
        tabla = new buscar(sql,new Object[]{"ID","Pez","Fecha","Evento"},4);
        tabla.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       Reporte re = new Reporte();
       if(re.reporteEvento()==1){
            JOptionPane.showMessageDialog( null, "Reporte Generado\nSe ha generado exitosamente el reporte","Reporte Generado",JOptionPane.INFORMATION_MESSAGE );
       }else{
       JOptionPane.showMessageDialog( null, "Reporte Fallido\nError al generar el reporte","Reporte Fallido",JOptionPane.ERROR_MESSAGE );
       }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       Reporte re = new Reporte();
       if(re.reportePez()==1){
            JOptionPane.showMessageDialog( null, "Reporte Generado\nSe ha generado exitosamente el reporte","Reporte Generado",JOptionPane.INFORMATION_MESSAGE );
       }else{
       JOptionPane.showMessageDialog( null, "Reporte Fallido\nError al generar el reporte","Reporte Fallido",JOptionPane.ERROR_MESSAGE );
       }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       Reporte re = new Reporte();
       if(re.reporteEspecie()==1){
            JOptionPane.showMessageDialog( null, "Reporte Generado\nSe ha generado exitosamente el reporte","Reporte Generado",JOptionPane.INFORMATION_MESSAGE );
       }else{
       JOptionPane.showMessageDialog( null, "Reporte Fallido\nError al generar el reporte","Reporte Fallido",JOptionPane.ERROR_MESSAGE );
       }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       Reporte re = new Reporte();
       if(re.reporteTanque()==1){
            JOptionPane.showMessageDialog( null, "Reporte Generado\nSe ha generado exitosamente el reporte","Reporte Generado",JOptionPane.INFORMATION_MESSAGE );
       }else{
       JOptionPane.showMessageDialog( null, "Reporte Fallido\nError al generar el reporte","Reporte Fallido",JOptionPane.ERROR_MESSAGE );
       }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Esp;
    private javax.swing.JMenuItem Evt;
    private javax.swing.JMenuItem Pez;
    private javax.swing.JMenuItem Tan;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenu consulta;
    private javax.swing.JPanel imagenP;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu reportes;
    private javax.swing.JMenuItem salida;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
